kind: project
metadata:
  name: pipe
spec:
  description: test
  params:
    label_column: label
  functions:
  - url: prep_data.py
    name: prep-data
    image: mlrun/mlrun
    handler: prep_data
    with_repo: true
  - url: hub://auto-trainer
    name: auto-trainer
  - url: hub://v2-model-server
    name: serve
  - url: hub://describe
    name: describe
  - url: gen_iris.py
    name: gen-iris
    image: mlrun/mlrun
    handler: iris_generator
    requirements:
    - requests
  workflows:
  - name: main
    path: ./kflow.py
    engine: kfp
  - name: newflow
    path: ./newflow.py
    handler: newpipe
  artifacts:
  - kind: artifact
    metadata:
      project: pipe
      key: data
    spec:
      target_path: https://s3.wasabisys.com/iguazio/data/iris/iris.data.raw.csv
  source: ./
  subpath: ''
  origin_url: ''
  load_source_on_run: true
  desired_state: online
